language: node_js
node_js:
- '6.11'
install: npm install
script: npm test
cache:
  directories:
  - node_modules
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^(development|qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
  - secure: cqyIiG9AChuxYZnVJ7wzgaT9CSBFMFLGtiEX0UQCphrtDjrC5ZhXJDlveLrhAQxosnUMcUem+E5jdA5ef9u7dFxNioIrlNKTcUG800cjhNP7ffRu3xIZMCQAeAnCv/S+efPhFpJbMcgpsItpQNXO7zrQJMhPgQBb80mre5Cx6RMIIb8SnkuT4L/XEeNqveymux52veV1UF6jpwPbozZ1z5O/koM4uQlQDUPb09QC7WoYN4WzOSDu44sgLGoPSjOer8RGQpSX44NFnzKGIGKnqIA3kadsHnK0jY4llHSABh19Ud5LSZqfpkrtzNuCFTg6SjYqBaHC4ACHVHYUzMUvsWJow/KTKStJSrjCv0gyxMEVGy/BmXOIMAZ5kN4nFjwL3RsbGG5NtYkg7YUKe4Dndf+ImcL2Yryq3rlFDwljWZ4JvasiwkTeR3M2CmChcJdn7xgFFRusabG4BVpici1tVpZ0njA5nKkXnkJnUxzbbsWNdpiQ+w6MGNJeW2quICcGjAQ5+t+qJMDZcUYgfgQXABttAxiA9ZAC5bpubPu8gy1yhttvC+8gFDXmANKNTblOrYS0ZEQotETyqLswHsCcuZaCppCrMMV9neJvFYUgmajderEzX1FLVQTdIq3p0EbWtNCiDdC17/TAdhUBvz/DkI2SpJkGsusdu90WwAEXaS8=
  - secure: a6kYiDWjzauz95FylsX9qEOeDER4s17Cjln4wAgpRl/GZ+dd7mTg9adljmHb3Dax6DbRo2CBW7a5aCRf33tder44D43eze77pgsgSkdUPCr7ZEHGITAWOM7xS+090CrfHQ1YfleEV9EeBVEw3t8kXkM5o7S7beh0mkBIZz2sgdP+hiJrE7jjc/vZspP41dLoXQ8u13vdQN4swFddomW7T+QR47ociRzmIJ+yRZH9mA5HoE4eBxve/uV9uS+nv/zlxD0uQZzNdi2M1G8kjgs19mHazrX9A386vLctCGobQhrDbHFwYztStrmQJoF0OzNzakiGDeC+qm9Q17o2m3azJ9Olqw0G+VI3ZiNSXvXnNNmpXVljfv/zevDP1Z7ZHzIZgsVNHvp7pXS7o7tznuqkSYU9B00MilzZ4sc3y45xFd/Z+oiy5rW3BDuJnqde/LdN9OzYXzdcSW7EvWTxTfA+5gO1gnF8XU8heIaaSBPuOuR96feIGQm3Pg459yWUEkOs/CmFD26OF1O/X4GrLkaAh+ZUqT7ap0MaYnmfK6LBV+uTluvWoyEAxUrVBz+91iOFgAUkmqS+PUTpgSba161ornJNq//mJ/cidbStdUdy8zP2LojkO6V9Q/Sr8vOc9ZZlKGsGeYRkLGo2jQ3rUhnV8sOgn5KNq7fXL8zk4/0hwYA=
  - secure: iZT/HPlOy46GW7tisCtN/MDz0Zj7+cTqSfSu/vHSPMEnj3KzKbTM7/m26NdA3VakEa036l4bUXGhBGk6Hc6fBF8pA9W21VxqQKzoF+4fJ/ZXKSiCSmzvWq4ELnzGLldiAvMfZV4JMe0fWWdL+JGn+9GsL3wt2bFOILvPWgxWrhdBt8PcPY0Fdq0ZquvxuQhQsS0Ejhcy0tRc4i6Ua8krfYkHzPqEsiV43cJP3IXiAqmcrxCRCZ3edoFxcoT3VYqH7vtbWr/kKJ419f68Iq+gEpFrAuIoq8eFXCrquwSs0EQ7AXmpxy1zypR52HUubtHhREXMV2Qw1py7aMZS32hG+/8UFEPamQYgN64Zckt4fkCG0ut4JjBQ5Nrj9FdNDuValdR2opmmOJopfzPxkyl9yHyKg/Cd80SscIRZSBHkKvp2VuI89MHsgi/AhkCeThJzX8xU3/r5Ea3g2NtndPGrTGaT64tcvrXZaRy6e9sej8+Fhe74Ti5nUkXdve3Kln3T7s1VEAjjUxrq3mHw+anZkNgC6XhQStButtk6cSsdcKmIJ/cuTElDgt3hkpVmEl5XeIYJYS1cvZ9OHxHgp+G69Pd62hlg9CudJjk1PIY/55MN9EvDwc0UTDFQUTzTGhxhe+m+ZQb6CimzKkKXkMKk+CvpLpDM9H/GngiAGtNGUIY=
