language: node_js
node_js:
- '6.11'
install: npm install
script: npm test
cache:
  directories:
  - node_modules
before_deploy:
- echo "All unit tests passed; Preparing to deploy $TRAVIS_BRANCH"
after_success:
- ENVIRONMENT_NAME=$TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then ENVIRONMENT_NAME=production; fi
deploy:
- provider: script
  skip_cleanup: true
  script: "./scripts/travis-deploy.sh $ENVIRONMENT_NAME"
  on:
    all_branches: true
    condition: "$ENVIRONMENT_NAME =~ ^(development|qa|production)$"
after_deploy: echo "Successfully executed deploy trigger for $TRAVIS_BRANCH"
env:
  global:
  - secure: i07rHoa01lSBzcQob/Tdt/K5UPYUS2/VLSPQEMLQoZi6oRVZNprY8i9/Xy+WyyeCoP/doPU1PXWQ4SVlJgizL0eahkTw33AiX54ZDq/3VfwXyTlaU40VKRXzDgYmB2Q2oHWr+mH8g7FeLb/EyHDu1OiidyZOMmsKEAIeqETxwxHeOsI0L1HcGZPu6zQcqIhOhvsFrWWjT/hgJHYuP8AEs9WJ0rCa/Vh6cPZcwB5m79hh080HfBJh1BX5Kjd9iMXoVvfTxVqmIN2h++0KLcqmULvHkan1RNLxT/54+brlFUdElFFVeCeVw0jb59ihP9oQbdEYUUYMreloxCOnhWVHcSQOl7aywMjndmyhjj2t8g2l/S1c2s9eXJJQWklvtsb07cXPoTD1XBEXrI/4Udmt8OumiV/U3n27re5Jsxf7mfi18PauwtH+6x9aqAJxFRvq2Cgc6RYaVjoNK6MgixREzhcwlbzhkztv3GGzVAHqrVgzCDpxpRWRjMZDVJYUfU6Zyt/d0+0OuA0TF/ku7PqfBdP1TFxtnblbEnnLEE6nYuovi9p9VR5374Fwziux+XAqCtEUEs/hXfMmiyyww93HesuKBN0hTENcYM54eruRM85/fVtY39tyS478nz8NyjV/cX7VJZx6Up5xVJVIaXtmjbzddsmiG1sOrMLeBQQYBjc=
  - secure: yjJrKg+Ye2C0w2WDuITVz8z51hkrfYbu3Ap8gHyCdZYZSze8mAJS0cwDb1OpKqyQarHSEk4O9RFANMlGnP64Su4rW/NYmMQ5PTlr+xkr1q/OwdtsUyKhmk9sFtz8pyYafGZPGl2+9gAdDB4jaae5yafBBvzQaWaurGlom34QtK6IgaXVQlsNASge7LqmRrLpi3kuBwf7Vs2XRl5HwnBeMEPr+dEiDX31YR472zmhxZ6mzyL0BhNmvrbpUlITlzigQkOXA81odsaLfJ6NHnBUzfGZzQoWOuJXd+6Lw9Mt0iTh+A/6c+So1VEVyemhtMIYA9knnvTaVe2kD7tHNlSMRxVc3SEmrhDk73LWBBYQXE3bYPlCrdkUcrQSHxGYEFwIWpj2v8k/ThnAwumdS/kEAKhxj3vGUJskzJkaQqkgtrvPSHcuKHy1PYlDJwdj/oVhfqsR7Mhou21Q+zMlJ2MnoEtQZSDBaB7532TYyVqPh8imBQ+rsHUDf6ykYmnP5gZ/QwCj72EYWncPc3cUyPcC5xvFdSbaQVLhqCHQ2rseJGVXk9sjtEe6ouhrYoHe3fpf22o/TSsWT67MaZIeGqf98HpvryVlq56N894SKFFhdhmcRu5lmD9Je/1ASWuVa8fiZ524n/se97bPBw5rgbCeNj5JDvNSgvQG3lJ8kjs6Ugk=
  - secure: iTP4pDX6aoYvjxlhD9zhtlg5KHmFrS7/+PvPLzsMYLLd7lTQfGHjNrYLRF7xugRm++5SCtHRmL9rsykHYPytn269Vgo6RTsJJuxM/ghY2xJ1mey0CwnrUu0tzNoL9ftHsVyJcmhh9VUTKpvUPfgN8tX8TA6IbBtUQYepxhymEpw0uqZJIhFFbSrUhWx4tjvgunXs63uRqGHM7vga8P+TgroFRV9L+qBGmmqvtOnI26284Y2PDnJtwFPw5wkoiG11iZWnpERBzonskMx7T5NeALJRJtiZiAtvVDkBPtiuVx/WIps/DGAjVDPulO3l2Z6oCG6pgvuHoq6jDcxk0F6MB4V7XYANfT6M4YvDkdf9FJ6oBcoSNbdNIxzuvyip5QgCeDcMJBgCQM6oZG6Pv7L956yrPgNWAKV2QbJPkqr1PpW5OUYDIkGtEisDwBxuCiSrdPpVcYvRONwzWD7SbE7VmdPRgoRaStgtug6fVvX4Ujia2w4pRX2BLNZWF1j3jdjqZ+f9B+YUiqKqDzFkQL0kYRII/JsbswxdHZdHypD5H2FZYplZ1HEWlQXYco94eJouE+Xh2gjwQ379kxYv9wReJFWgYV6g7FJktIBNDBND24NlJ6bSYkT2MF5+R1lxkvlbGeFQMwOghVJu8iSSjZma3EHmwK21bXraAz3qOZBFL6A=
